import { TestCase } from './testingTypes';

export const TEST_CASES: TestCase[] = [
  {
    id: 'TC001',
    name: 'Budget Constraint Respected',
    description: 'Decision Agent must not return packages exceeding the user-specified budget.',
    category: 'AGENT',
    input: { budget: 40000, travellers: 2, nights: 4, destination: 'Mussoorie' },
    expectedOutput: { packageCost: 31300, withinBudget: true, rejected: false },
  },
  {
    id: 'TC002',
    name: 'Date Constraint Respected',
    description: 'All bookings must fall within the user-specified travel window.',
    category: 'AGENT',
    input: { startDate: '2026-09-15', endDate: '2026-09-18', nights: 4 },
    expectedOutput: { checkIn: '2026-09-15', checkOut: '2026-09-18', durationValid: true },
  },
  {
    id: 'TC003',
    name: 'Traveller Count Accuracy',
    description: 'Package Builder must provision seats/rooms for the correct number of travellers.',
    category: 'AGENT',
    input: { travellers: 2 },
    expectedOutput: { trainSeats: 2, hotelOccupancy: 2, transferCapacity: 2 },
  },
  {
    id: 'TC004',
    name: 'Weather Preference Filter',
    description: 'Decision Agent must downrank destinations with HIGH rain risk in September.',
    category: 'AGENT',
    input: { month: 'September', rainPreference: 'low', destination: 'Mussoorie' },
    expectedOutput: { rainRisk: 'MEDIUM', recommended: true, blockedByRain: false },
  },
  {
    id: 'TC005',
    name: 'Transport Preference: Train',
    description: 'When user specifies "train preferred", AI must select train over flight first.',
    category: 'AGENT',
    input: { transportPreference: 'train', origin: 'Delhi', destination: 'Dehradun' },
    expectedOutput: { selectedMode: 'TRAIN', flightConsidered: true, trainChosen: true },
  },
  {
    id: 'TC006',
    name: 'Price Change Detection at Checkout',
    description: 'Revalidation must detect a price increase and block checkout until user reviews.',
    category: 'PAYMENT',
    input: { quotedPrice: 31300, livePrice: 32100 },
    expectedOutput: { priceChanged: true, checkoutBlocked: true, delta: 800 },
  },
  {
    id: 'TC007',
    name: 'Hotel Sold-Out — Recovery Triggered',
    description: 'If hotel becomes unavailable post-payment, Recovery Agent must be triggered.',
    category: 'RECOVERY',
    input: { hotelStatus: 'SOLD_OUT', paymentStatus: 'CAPTURED' },
    expectedOutput: { recoveryTriggered: true, alternativesFound: true, bookingStatus: 'PARTIALLY_CONFIRMED' },
  },
  {
    id: 'TC008',
    name: 'Train Delay — Transfer Conflict Detected',
    description: 'An 80-minute train delay must be detected as causing a transfer conflict.',
    category: 'RECOVERY',
    input: { trainDelayMinutes: 80, transferBufferMinutes: 30 },
    expectedOutput: { conflictDetected: true, severity: 'MEDIUM', transferRescheduled: true },
  },
  {
    id: 'TC009',
    name: 'Cab Unavailable — Alternative Sourced',
    description: 'If original cab is unavailable, Recovery Agent must source 3 alternatives.',
    category: 'RECOVERY',
    input: { cabStatus: 'UNAVAILABLE', tripId: 'SB-TRIP-MUSSOORIE-4D' },
    expectedOutput: { alternativeCount: 3, bestOptionSelected: true, userApprovalRequired: false },
  },
  {
    id: 'TC010',
    name: 'Activity Cancellation — Replacement Found',
    description: 'Provider-cancelled activity must trigger alternative search + user approval.',
    category: 'RECOVERY',
    input: { activityStatus: 'CANCELLED', requiresApproval: true },
    expectedOutput: { replacementFound: true, userApprovalRequired: true, itineraryUpdated: true },
  },
  {
    id: 'TC011',
    name: 'Payment Failure — Booking NOT Started',
    description: 'Critical: Failed payment must never trigger any booking action.',
    category: 'PAYMENT',
    input: { paymentStatus: 'FAILED', webhookReceived: false },
    expectedOutput: { bookingStarted: false, bookingStatus: 'NOT_STARTED', refundNeeded: false },
  },
  {
    id: 'TC012',
    name: 'Duplicate Webhook — Idempotency',
    description: 'Same Razorpay payment webhook sent twice must result in exactly one booking.',
    category: 'IDEMPOTENCY',
    input: { webhookCount: 2, paymentId: 'pay_test_duplicate' },
    expectedOutput: { bookingsCreated: 1, secondWebhookIgnored: true, idempotencyKey: 'pay_test_duplicate' },
  },
  {
    id: 'TC013',
    name: 'Provider Timeout — Retry + Fallback',
    description: 'Hotel provider timeout must trigger retry, then fallback provider.',
    category: 'PROVIDER',
    input: { hotelProviderResponse: 'TIMEOUT', retryCount: 2 },
    expectedOutput: { retriesAttempted: 2, fallbackUsed: true, bookingSucceeded: true },
  },
  {
    id: 'TC014',
    name: 'Unauthorized Trip Access Blocked',
    description: 'User A must receive 403 when accessing User B\'s trip.',
    category: 'SECURITY',
    input: { requestingUserId: 'USR_A', tripOwnerId: 'USR_B', action: 'VIEW_TRIP' },
    expectedOutput: { decision: 'DENY', statusCode: 403, reason: 'You do not own this resource.' },
  },
  {
    id: 'TC015',
    name: 'Recovery Failure — No Alternatives',
    description: 'If no hotel alternatives exist after sold-out, system must surface RECOVERY_FAILED and not hang.',
    category: 'RECOVERY',
    input: { alternativesAvailable: 0, originalStatus: 'SOLD_OUT' },
    expectedOutput: { recoveryStatus: 'FAILED', supportWorkflowTriggered: true, userNotified: true },
  },
];
